openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    Swagger at [https://swagger.io](https://swagger.io). In the 
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: timeoff
    description: Everything about your time off
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /timeoff:
    post:
      tags:
        - timeoff
      summary: Add a time off
      description: Add a time off to a user
      operationId: addTimeOff
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTimeOff"
        required: true
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeOff"
  /timeoff/query:
    get:
      tags:
        - timeoff
      summary: Query time off
      description: Query time off using different parameters
      operationId: queryTimeOff
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold

components:
  schemas:
    TimeOff:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        user_id:
          type: integer
          format: int64
          example: 10
        from:
          type: string
          format: date
        from_bound:
          $ref: "#/components/schemas/DateBound"
        to:
          type: string
          format: date
        to_bound:
          $ref: "#/components/schemas/DateBound"

    DateBound:
      type: string
      description: Inclusive (i) or exclusive(e) date
      enum:
        - i
        - e

    CreateTimeOff:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
          example: 10
        from:
          type: string
          format: date

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: "##default"
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header

